export const AmazonTemplates = [
    {
        title: "أفضل الهواتف الذكية في أمازون",
        slug: "best-smartphones",
        category: "electronics",
        intent: "commercial",
    },
    {
        title: "أرخص لابتوبات للطلاب",
        slug: "student-laptops",
        category: "electronics",
        intent: "budget",
    },
    {
        title: "مقارنة أجهزة بلايستيشن وإكس بوكس",
        slug: "gaming-consoles-comparison",
        category: "gaming",
        intent: "comparison",
    },
    {
        title: "أفضل عطور رجالية بأسعار مناسبة",
        slug: "best-mens-perfumes",
        category: "beauty",
        intent: "commercial",
    },
    {
        title: "أدوات مطبخ ذكية توفر وقتك",
        slug: "smart-kitchen-appliances",
        category: "home",
        intent: "commercial",
    },
    {
        title: "أفضل منتجات العناية بالبشرة",
        slug: "best-skincare-products",
        category: "beauty",
        intent: "commercial",
    },
    {
        title: "تجميعة بي سي جيمنج اقتصادية",
        slug: "budget-gaming-pc-build",
        category: "gaming",
        intent: "budget",
    },
    {
        title: "أفضل الساعات الذكية الرياضية",
        slug: "best-smartwatches",
        category: "electronics",
        intent: "commercial",
    },
    {
        title: "مستلزمات الأطفال وحديثي الولادة",
        slug: "baby-essentials",
        category: "family",
        intent: "commercial",
    },
    {
        title: "أرخص طابعات منزلية اقتصادية",
        slug: "budget-home-printers",
        category: "electronics",
        intent: "budget",
    },
    {
        title: "أفضل ماكينات صنع القهوة",
        slug: "best-coffee-makers",
        category: "home",
        intent: "commercial",
    },
    {
        title: "معدات تصوير للمبتدئين في يوتيوب",
        slug: "youtube-starter-gear",
        category: "electronics",
        intent: "commercial",
    },
    {
        title: "أفضل شاشات قيمنق 144Hz",
        slug: "best-144hz-gaming-monitors",
        category: "gaming",
        intent: "commercial",
    },
    {
        title: "منتجات العناية بالشعر الكيرلي",
        slug: "curly-hair-products",
        category: "beauty",
        intent: "commercial",
    },
    {
        title: "أفضل باور بانك للسفر",
        slug: "best-travel-power-banks",
        category: "electronics",
        intent: "commercial",
    },
    {
        title: "أرخص سماعات بلوتوث عازلة للضوضاء",
        slug: "budget-anc-headphones",
        category: "electronics",
        intent: "budget",
    },
    {
        title: "أدوات رياضية منزلية متكاملة",
        slug: "home-gym-equipment",
        category: "sports",
        intent: "commercial",
    },
    {
        title: "أفضل أجهزة التابلت للدراسة",
        slug: "best-tablets-for-students",
        category: "electronics",
        intent: "commercial",
    },
    {
        title: "مستحضرات تجميل كورية أصلية",
        slug: "korean-skincare-products",
        category: "beauty",
        intent: "commercial",
    },
    {
        title: "أفضل حقائب السفر الصلبة",
        slug: "best-hardshell-luggage",
        category: "travel",
        intent: "commercial",
    },
    {
        title: "أجهزة تنقية الهواء المنزلية",
        slug: "home-air-purifiers",
        category: "home",
        intent: "commercial",
    },
    {
        title: "أرخص مكانس كهربائية روبوتية",
        slug: "budget-robot-vacuums",
        category: "home",
        intent: "budget",
    },
    {
        title: "أفضل أجهزة إزالة الشعر بالليزر",
        slug: "laser-hair-removal-devices",
        category: "beauty",
        intent: "commercial",
    },
    {
        title: "معدات تخييم ورحلات برية",
        slug: "camping-and-outdoor-gear",
        category: "sports",
        intent: "commercial",
    },
    {
        title: "أفضل لوحات مفاتيح ميكانيكية",
        slug: "best-mechanical-keyboards",
        category: "gaming",
        intent: "commercial",
    },
    {
        title: "مستلزمات العناية بالحيوانات الأليفة",
        slug: "pet-care-essentials",
        category: "pets",
        intent: "commercial",
    },
    {
        title: "أفضل أجهزة قياس ضغط الدم والسكر",
        slug: "health-monitor-devices",
        category: "health",
        intent: "commercial",
    },
    {
        title: "طاولات جيمنج احترافية",
        slug: "pro-gaming-desks",
        category: "gaming",
        intent: "commercial",
    },
    {
        title: "أفضل كاميرات مراقبة منزلية ذكية",
        slug: "smart-home-security-cameras",
        category: "home",
        intent: "commercial",
    },
    {
        title: "مقارنة أجهزة كيندل للقراءة",
        slug: "kindle-e-readers-comparison",
        category: "electronics",
        intent: "comparison",
    }
];
